//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLICON_ConUni_DOTNET_GR04.ConUniRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ConUniRef.IWSConUni")]
    public interface IWSConUni {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSConUni/CentimetrosAPulgadas", ReplyAction="http://tempuri.org/IWSConUni/CentimetrosAPulgadasResponse")]
        float CentimetrosAPulgadas(float cm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSConUni/CentimetrosAPulgadas", ReplyAction="http://tempuri.org/IWSConUni/CentimetrosAPulgadasResponse")]
        System.Threading.Tasks.Task<float> CentimetrosAPulgadasAsync(float cm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSConUni/PulgadasACentimetros", ReplyAction="http://tempuri.org/IWSConUni/PulgadasACentimetrosResponse")]
        float PulgadasACentimetros(float inch);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSConUni/PulgadasACentimetros", ReplyAction="http://tempuri.org/IWSConUni/PulgadasACentimetrosResponse")]
        System.Threading.Tasks.Task<float> PulgadasACentimetrosAsync(float inch);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSConUni/CelsiusAFahrenheit", ReplyAction="http://tempuri.org/IWSConUni/CelsiusAFahrenheitResponse")]
        float CelsiusAFahrenheit(float c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSConUni/CelsiusAFahrenheit", ReplyAction="http://tempuri.org/IWSConUni/CelsiusAFahrenheitResponse")]
        System.Threading.Tasks.Task<float> CelsiusAFahrenheitAsync(float c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSConUni/FahrenheitACelsius", ReplyAction="http://tempuri.org/IWSConUni/FahrenheitACelsiusResponse")]
        float FahrenheitACelsius(float f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSConUni/FahrenheitACelsius", ReplyAction="http://tempuri.org/IWSConUni/FahrenheitACelsiusResponse")]
        System.Threading.Tasks.Task<float> FahrenheitACelsiusAsync(float f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSConUni/KilogramosALibras", ReplyAction="http://tempuri.org/IWSConUni/KilogramosALibrasResponse")]
        float KilogramosALibras(float kg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSConUni/KilogramosALibras", ReplyAction="http://tempuri.org/IWSConUni/KilogramosALibrasResponse")]
        System.Threading.Tasks.Task<float> KilogramosALibrasAsync(float kg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSConUni/LibrasAKilogramos", ReplyAction="http://tempuri.org/IWSConUni/LibrasAKilogramosResponse")]
        float LibrasAKilogramos(float lb);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSConUni/LibrasAKilogramos", ReplyAction="http://tempuri.org/IWSConUni/LibrasAKilogramosResponse")]
        System.Threading.Tasks.Task<float> LibrasAKilogramosAsync(float lb);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWSConUniChannel : CLICON_ConUni_DOTNET_GR04.ConUniRef.IWSConUni, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSConUniClient : System.ServiceModel.ClientBase<CLICON_ConUni_DOTNET_GR04.ConUniRef.IWSConUni>, CLICON_ConUni_DOTNET_GR04.ConUniRef.IWSConUni {
        
        public WSConUniClient() {
        }
        
        public WSConUniClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSConUniClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSConUniClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSConUniClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public float CentimetrosAPulgadas(float cm) {
            return base.Channel.CentimetrosAPulgadas(cm);
        }
        
        public System.Threading.Tasks.Task<float> CentimetrosAPulgadasAsync(float cm) {
            return base.Channel.CentimetrosAPulgadasAsync(cm);
        }
        
        public float PulgadasACentimetros(float inch) {
            return base.Channel.PulgadasACentimetros(inch);
        }
        
        public System.Threading.Tasks.Task<float> PulgadasACentimetrosAsync(float inch) {
            return base.Channel.PulgadasACentimetrosAsync(inch);
        }
        
        public float CelsiusAFahrenheit(float c) {
            return base.Channel.CelsiusAFahrenheit(c);
        }
        
        public System.Threading.Tasks.Task<float> CelsiusAFahrenheitAsync(float c) {
            return base.Channel.CelsiusAFahrenheitAsync(c);
        }
        
        public float FahrenheitACelsius(float f) {
            return base.Channel.FahrenheitACelsius(f);
        }
        
        public System.Threading.Tasks.Task<float> FahrenheitACelsiusAsync(float f) {
            return base.Channel.FahrenheitACelsiusAsync(f);
        }
        
        public float KilogramosALibras(float kg) {
            return base.Channel.KilogramosALibras(kg);
        }
        
        public System.Threading.Tasks.Task<float> KilogramosALibrasAsync(float kg) {
            return base.Channel.KilogramosALibrasAsync(kg);
        }
        
        public float LibrasAKilogramos(float lb) {
            return base.Channel.LibrasAKilogramos(lb);
        }
        
        public System.Threading.Tasks.Task<float> LibrasAKilogramosAsync(float lb) {
            return base.Channel.LibrasAKilogramosAsync(lb);
        }
    }
}
