//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSConUniServiceReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSConUniServiceReference.IWSConUni")]
    public interface IWSConUni
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSConUni/CentimetrosAPulgadas", ReplyAction="http://tempuri.org/IWSConUni/CentimetrosAPulgadasResponse")]
        System.Threading.Tasks.Task<float> CentimetrosAPulgadasAsync(float cm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSConUni/PulgadasACentimetros", ReplyAction="http://tempuri.org/IWSConUni/PulgadasACentimetrosResponse")]
        System.Threading.Tasks.Task<float> PulgadasACentimetrosAsync(float inch);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSConUni/CelsiusAFahrenheit", ReplyAction="http://tempuri.org/IWSConUni/CelsiusAFahrenheitResponse")]
        System.Threading.Tasks.Task<float> CelsiusAFahrenheitAsync(float c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSConUni/FahrenheitACelsius", ReplyAction="http://tempuri.org/IWSConUni/FahrenheitACelsiusResponse")]
        System.Threading.Tasks.Task<float> FahrenheitACelsiusAsync(float f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSConUni/KilogramosALibras", ReplyAction="http://tempuri.org/IWSConUni/KilogramosALibrasResponse")]
        System.Threading.Tasks.Task<float> KilogramosALibrasAsync(float kg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSConUni/LibrasAKilogramos", ReplyAction="http://tempuri.org/IWSConUni/LibrasAKilogramosResponse")]
        System.Threading.Tasks.Task<float> LibrasAKilogramosAsync(float lb);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IWSConUniChannel : WSConUniServiceReference.IWSConUni, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class WSConUniClient : System.ServiceModel.ClientBase<WSConUniServiceReference.IWSConUni>, WSConUniServiceReference.IWSConUni
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WSConUniClient() : 
                base(WSConUniClient.GetDefaultBinding(), WSConUniClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IWSConUni.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSConUniClient(EndpointConfiguration endpointConfiguration) : 
                base(WSConUniClient.GetBindingForEndpoint(endpointConfiguration), WSConUniClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSConUniClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WSConUniClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSConUniClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WSConUniClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSConUniClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<float> CentimetrosAPulgadasAsync(float cm)
        {
            return base.Channel.CentimetrosAPulgadasAsync(cm);
        }
        
        public System.Threading.Tasks.Task<float> PulgadasACentimetrosAsync(float inch)
        {
            return base.Channel.PulgadasACentimetrosAsync(inch);
        }
        
        public System.Threading.Tasks.Task<float> CelsiusAFahrenheitAsync(float c)
        {
            return base.Channel.CelsiusAFahrenheitAsync(c);
        }
        
        public System.Threading.Tasks.Task<float> FahrenheitACelsiusAsync(float f)
        {
            return base.Channel.FahrenheitACelsiusAsync(f);
        }
        
        public System.Threading.Tasks.Task<float> KilogramosALibrasAsync(float kg)
        {
            return base.Channel.KilogramosALibrasAsync(kg);
        }
        
        public System.Threading.Tasks.Task<float> LibrasAKilogramosAsync(float lb)
        {
            return base.Channel.LibrasAKilogramosAsync(lb);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IWSConUni))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IWSConUni))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:65462/espe.edu.monster.servicio/WSConUni.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return WSConUniClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IWSConUni);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return WSConUniClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IWSConUni);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IWSConUni,
        }
    }
}
